# config.toml

# Warning: all members of the community will read JSON form data in this file to render the frontend.

# most of the objects declarable here have both `name` and `id`, `id` is for code and `name` if for humans. For example, changing the name a channel will not change the related messages, changing `id` will.

hostname = "localhost"
# public keys of highest privileged users that can edit this config remotely and in general don't need role permissions
roots = [
	"039716e3ac965106a984801a50945124adf5fcba0c6e67f9eac6e3528a90a7e501",
	"030c6c636d00c28890b310dd979610e5019d26c2fb97db230de3eb267f5899c35b",
]
public = "client/public"
	
[[roles]]
id = 0
name = "admin"

[[roles]]
id = 1
name = "other role"

# simplest channel configuration, the channel is just a historical sequence
# of messages
[[channels]]
id = 0
name = "channello"
group = "grouplo"

[[channels]]
id = 2
name = "channello3"
group = "grouplo"
# if user does not have a role in the list, he will fall back to this
default_permissions = { write = false }
roles = [
	# allow only admins to read and send huge messages
	{ id = 0, max_message_length = 10000 },
	# disallow `other role`s from reading
	{ id = 1, read = false },
]

[[channels]]
id = 3
name = "voicechat"
group = "voices"
# assuming voice chat is enabled, presence of this filed will attach voice chat to the channel
voice = { max_participants = 10 }
